BEGIN;
ALTER TABLE digital_fpos ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE digital_fpos ADD COLUMN IF NOT EXISTS office_address TEXT;
ALTER TABLE digital_fpos ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION CHECK(latitude BETWEEN -90 AND 90);
ALTER TABLE digital_fpos ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION CHECK(longitude BETWEEN -180 AND 180);
COMMIT;
