'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Camera, ImagePlus, Send, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { getApiUrl } from '@/lib/api';
import UserAvatar from '@/app/components/UserAvatar';
import PostCard, { SocialPost } from '@/app/components/PostCard';

export default function PostsPage() {
 const router=useRouter(), {user,loading}=useAuth(); const [posts,setPosts]=useState<SocialPost[]>([]),[content,setContent]=useState(''),[image,setImage]=useState(''),[audience,setAudience]=useState('everyone'),[busy,setBusy]=useState(false),[error,setError]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{if(!user?.id)return;const r=await fetch(getApiUrl(`/api/posts?userId=${encodeURIComponent(user.id)}&viewerId=${encodeURIComponent(user.id)}`));if(r.ok)setPosts(await r.json())},[user?.id]); useEffect(()=>{void load()},[load]);
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!f.type.startsWith('image/')||f.size>10485760)return setError('Choose an image smaller than 10MB.');setBusy(true);const b=new FormData();b.append('file',f);const r=await fetch(getApiUrl('/api/upload'),{method:'POST',body:b});const d=await r.json();r.ok?setImage(d.url):setError(d.error||'Upload failed');setBusy(false)};
 const publish=async()=>{if(!user?.id||!content.trim())return;setBusy(true);const r=await fetch(getApiUrl('/api/posts'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:user.id,content,image_url:image||null,audience})});if(r.ok){setContent('');setImage('');await load()}else setError((await r.json()).error||'Could not publish post');setBusy(false)};
 const remove=async(id:number)=>{if(!user?.id||!confirm('Delete this post?'))return;const r=await fetch(getApiUrl(`/api/posts?id=${id}&userId=${encodeURIComponent(user.id)}`),{method:'DELETE'});if(r.ok)setPosts(v=>v.filter(p=>p.id!==id))};
 if(loading)return <div className="grid min-h-screen place-items-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-green-600 border-t-transparent"/></div>;
 return <main className="min-h-screen bg-gray-50 pb-12"><header className="sticky top-0 z-20 border-b bg-white"><div className="mx-auto flex max-w-3xl items-center gap-3 px-4 py-3"><button onClick={()=>router.back()} className="rounded-full p-2 hover:bg-gray-100"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="font-black">My Posts</h1><p className="text-xs text-gray-500">Share updates with the CoFarmz network</p></div></div></header><section className="mx-auto max-w-3xl space-y-5 p-4">
 {user?.id&&<div className="rounded-3xl border bg-white p-4 shadow-sm"><div className="flex gap-3"><UserAvatar image={user.image||''} name={user.name||'User'} size={42}/><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={3000} rows={4} placeholder="Share an update, requirement, opportunity or announcement…" className="min-w-0 flex-1 resize-none rounded-xl border p-3 text-sm outline-none focus:border-green-500"/></div>{image&&<div className="relative mt-3"><img src={image} alt="Preview" className="max-h-80 w-full rounded-2xl object-cover"/><button onClick={()=>setImage('')} className="absolute right-2 top-2 rounded-full bg-black/60 p-2 text-white"><X className="h-4 w-4"/></button></div>}<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>fileRef.current?.click()} className="flex items-center gap-2 rounded-xl bg-green-50 px-3 py-2 text-xs font-bold text-green-700"><Camera className="h-4 w-4"/>Add image</button><input ref={fileRef} type="file" accept="image/*" onChange={upload} className="hidden"/><select value={audience} onChange={e=>setAudience(e.target.value)} className="rounded-xl border px-3 text-xs font-bold"><option value="everyone">Everyone</option><option value="farmer">Farmers only</option><option value="buyer">Buyers only</option></select><button onClick={publish} disabled={!content.trim()||busy} className="ml-auto flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><Send className="h-4 w-4"/>{busy?'Working…':'Post'}</button></div>{error&&<p className="mt-3 text-sm font-bold text-red-600">{error}</p>}</div>}
 <div className="space-y-4">{posts.length?posts.map(p=><PostCard key={p.id} post={p} currentUserId={user?.id} own onDelete={()=>remove(p.id)}/>):<div className="rounded-2xl border border-dashed bg-white py-12 text-center text-sm text-gray-500"><ImagePlus className="mx-auto mb-2 h-8 w-8"/>No posts yet.</div>}</div>
 </section></main>;
}
