'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {authClient} from '@/lib/auth-client';
import {fpoFetch} from '@/lib/fpo-fetch';
export default function FpoDashboard(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;fpoFetch('/api/fpo/manager',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
 async function change(e:React.FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('New passwords do not match');return;}setBusy(true);try{const r=await fpoFetch('/api/fpo/manager',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:current,newPassword:password})});const d=await r.json();if(!r.ok)throw new Error(d.error);await authClient.signOut();window.location.assign('/fpo/login');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-3xl space-y-5 p-6"><h1 className="text-3xl font-bold text-green-800">Digital FPO dashboard</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{!data?<><p>{error?'Sign in with your assigned FPO account.':'Loading FPO…'}</p><Link href="/fpo/login" className="underline">FPO login</Link></>:<><section className="rounded-xl border p-4"><h2 className="text-xl font-bold">{data.manager.name}</h2><p>{data.manager.district}, {data.manager.state}</p><p>Login email: {data.manager.email}</p><p>Status: {data.manager.status}</p></section>{data.manager.must_change_password?<p className="rounded bg-amber-50 p-3">Set your own password to access your FPO. After saving, sign in again with your new password.</p>:data.manager.status==='active'?<section><h2 className="text-xl font-bold">Assigned farmers ({data.farmers.length})</h2><ul className="mt-3 space-y-2">{data.farmers.map((f:any)=><li key={f.id} className="rounded border p-3">{f.name}</li>)}</ul>{!data.farmers.length&&<p>No farmers assigned yet.</p>}</section>:<p>Your FPO is inactive. Contact your admin.</p>}<form onSubmit={change} className="space-y-3 rounded-xl border p-4"><h2 className="font-bold">{data.manager.must_change_password?'Set your password':'Change password'}</h2><label className="block">Current password<input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} className="block w-full rounded border p-2"/></label><label className="block">New password (12–128 characters)<input required minLength={12} maxLength={128} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="block w-full rounded border p-2"/></label><label className="block">Confirm new password<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="block w-full rounded border p-2"/></label><button disabled={busy} className="rounded bg-green-700 px-4 py-2 text-white">{busy?'Saving…':'Save password and sign out'}</button></form><button className="underline" onClick={async()=>{await authClient.signOut();window.location.assign('/fpo/login');}}>Sign out</button></>}</main>;
}
