'use client';
import { useEffect, useState } from 'react';
import { fpoFetch } from '@/lib/fpo-fetch';
export default function FpoCredentials({ fpoId }: { fpoId: string }) {
  const [account,setAccount]=useState<any>(null),[generatedEmail,setGeneratedEmail]=useState('');
  const [secret,setSecret]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  useEffect(()=>{let cancelled=false;setSecret(null);setLoaded(false);fpoFetch(`/api/admin/fpo/credentials?fpoId=${encodeURIComponent(fpoId)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!cancelled){setAccount(d.account);setGeneratedEmail(d.generatedEmail);setLoaded(true);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[fpoId]);
  async function generate(){setBusy(true);setError('');setSecret(null);try{const r=await fpoFetch('/api/admin/fpo/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fpoId,action:account?'reset':'create'})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSecret(d);setAccount({email:d.email,must_change_password:true});}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <section className="my-4 space-y-3 rounded-xl border p-4"><h2 className="font-bold">FPO login credentials</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}{!loaded?<p>Loading account details…</p>:<>{account?<><p>Login email: <strong>{account.email}</strong></p><p className="text-sm">{account.must_change_password?'Password change required at next login.':'Manager has set their own password.'}</p></>:<p className="break-all">Automatic login email: <strong>{generatedEmail}</strong></p>}<p className="text-sm text-gray-600">Temporary passwords appear once. Resetting signs the manager out and requires a new password.</p><button type="button" disabled={busy} onClick={generate} className="rounded bg-green-700 px-4 py-2 text-white disabled:opacity-50">{busy?'Generating…':account?'Reset temporary password':'Create FPO login'}</button></>}{secret&&<div role="status" className="space-y-2 rounded bg-green-50 p-3"><p>Email: {secret.email}</p><p className="break-all">Temporary password: <code>{secret.temporaryPassword}</code></p><p className="break-all">Login: {typeof window!=='undefined'?window.location.origin:''}/fpo/login</p><button type="button" className="underline" onClick={async()=>{try{await navigator.clipboard.writeText(`FPO login: ${window.location.origin}/fpo/login\nEmail: ${secret.email}\nTemporary password: ${secret.temporaryPassword}\nPlease change your password after signing in.`);}catch{setError('Copy unavailable. Select and copy the credentials above.');}}}>Copy credentials to share</button><button type="button" className="ml-4 underline" onClick={()=>setSecret(null)}>Hide password</button></div>}</section>;
}
